### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by Jevin754** [zh217/torch-asg#1]
Hi, I try to install torch-asg, but there is an error "command 'gcc' failed with exit status 1" . Could you please tell me which gcc version you use, so that I can try to install using the same settings. Thanks you so much for the help and contribution.

**Comment by zh217** [comment]
Hi, since the project is still in active development, things will break a lot I guess. If you can wait several weeks I think everything will become much more stable.

That said, if you really want to try it now, please clone the newest master branch of the project and install it with

```bash
DISTUTILS_DEBUG=1 pip -v install -e .
```
On ubuntu 18 with python 3.7 and pytorch 1.0.1 the CPU version should now work. There is still some work to be done before the GPU version can be used.
